/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Administrador
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIngresoDocentes = new javax.swing.JButton();
        btnBuscarDocentes = new javax.swing.JButton();
        btnIngresoLicencias = new javax.swing.JButton();
        btnBuscarLicencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Licencias");

        btnIngresoDocentes.setText("Ingresar Docentes");
        btnIngresoDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoDocentesActionPerformed(evt);
            }
        });

        btnBuscarDocentes.setText("Buscar Docentes");
        btnBuscarDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocentesActionPerformed(evt);
            }
        });

        btnIngresoLicencias.setText("Ingreso Licencias");
        btnIngresoLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoLicenciasActionPerformed(evt);
            }
        });

        btnBuscarLicencias.setText("Buscar Licencias");
        btnBuscarLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLicenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarDocentes)
                    .addComponent(btnBuscarLicencias))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresoLicencias)
                    .addComponent(btnIngresoDocentes))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresoLicencias)
                    .addComponent(btnBuscarLicencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarDocentes)
                    .addComponent(btnIngresoDocentes))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoDocentesActionPerformed
        // TODO add your handling code here:
         IngresoDocentes ventana = new IngresoDocentes();
    ventana.setVisible(true);
    this.setVisible(false);

    }//GEN-LAST:event_btnIngresoDocentesActionPerformed

    private void btnBuscarDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocentesActionPerformed
        // TODO add your handling code here:
  BuscarDocentes ventana = new BuscarDocentes();
    ventana.setVisible(true);
    this.setVisible(false);

    }//GEN-LAST:event_btnBuscarDocentesActionPerformed

    private void btnIngresoLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoLicenciasActionPerformed
        // TODO add your handling code here:
         IngresoLicencias ventana = new IngresoLicencias();
    ventana.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnIngresoLicenciasActionPerformed

    private void btnBuscarLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLicenciasActionPerformed
        // TODO add your handling code here:
         BuscarLicencias ventana = new BuscarLicencias();
    ventana.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnBuscarLicenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDocentes;
    private javax.swing.JButton btnBuscarLicencias;
    private javax.swing.JButton btnIngresoDocentes;
    private javax.swing.JButton btnIngresoLicencias;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
